name: Releases Bot
on:
  release:
    types: [published]

jobs:
  jsr:
    name: Ship to jsr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Publish package
        run: deno publish